### ISSUE TITLE
Gulp4 error

### ISSUE THREAD

**Issue by MatheusRV** [h5bp/html5-boilerplate#2056]
**I'm submitting a ...**

- [X] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (below))

## Bug reports

```
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/mnt/d/Cloud/OneDrive/Dev/SaaS-Catalog/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/mnt/d/Cloud/OneDrive/Dev/SaaS-Catalog/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/mnt/d/Cloud/OneDrive/Dev/SaaS-Catalog/gulpfile.babel.js:78:6)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at loader (/mnt/d/Cloud/OneDrive/Dev/SaaS-Catalog/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/d/Cloud/OneDrive/Dev/SaaS-Catalog/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)

```
Update gulp v3 to gulp v4. https://fettblog.eu/gulp-4-parallel-and-series/

**Comment by caraya** [comment]
@MatheusRV 
The default gulpfile will not work with Gulp 3 as it has changed the way you run tasks in sequence and parallel. In order to make it work you need to do the following:

1. Update Gulp (npm i -g gulp@4.0)
2. Update your project Gulp (npm i -D gulp@next)
3.  Modify the gulpfile to work with the new task syntax (A good tutorial: [How do I update to Gulp 4?](https://www.liquidlight.co.uk/blog/article/how-do-i-update-to-gulp-4/))

If you haven't updated the gulpfile then it's working as intended and will work fined with Gulp 3, included in `package.json`. 

@roblarsen 

Does it make sense to update to Gulp 4 or create an alternate gulpfile for people who are using version 4 already? I can work on it if it makes sense

Otherwise I think this bug can be closed. The file is working as designed.

**Comment by roblarsen** [comment]
Sorry, I've been busy with other things. @caraya  I'm not a heavy Gulp user (I basically just use it here and didn't write this build process originally,) is there much benefit to upgrading for our meager build needs? If you're interested in doing the upgrade and think there's benefit I'd welcome the PR.

**Comment by caraya** [comment]
I don't think so. Gulp 4 changes the task signatures without, in my opinion, adding any real benefit. I haven't seen much interest in upgrading to Gulp 4 in issues or PRs either

**Comment by roblarsen** [comment]
Thanks @caraya
